choco install vcredist-all --version 1.0.1 -y
choco install powershell-core --version 7.3.5 -y
choco install 7zip-zstd --version 1.5.2.1 -y
choco install git --version 2.41.0 -y
choco install git-lfs --version 3.3.0 -y
choco install gitlab-runner --version 16.0.2 -y
choco install aria2 --version 1.36.0 -y
choco install jq --version 1.6 -y
choco install yq --version 4.33.3 -y
choco install vswhere --version 3.1.4 -y
choco install curl --version 8.1.2 -y
choco install wget --version 1.21.4 -y
choco install nuget.commandline --version 6.6.1 -y
